### ISSUE TITLE
Check the database adaptor, fails with sqlite 

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/fixturize#2]
## The problem

One of our plugins was using sqlite and I would prefer to stick to it. The problem is it uses a few fixtures from our main app (depends on it anyway) and the app is using Fixturize.

Now the problem is that I'm getting an error:

```sh
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

\vendor\friendsofcake\fixturize\src\TestSuite\Fixture\ChecksumTestFixture.php (line 106)
########## DEBUG ##########
'CHECKSUM TABLE wa_cms_pages'
###########################
PHP Fatal error:  Uncaught Cake\Core\Exception\Exception: Unable to insert fixture "Psa\Cms\Test\Fixture\CmsPagesFixture" in "Psa\Cms\Test\TestCase\Model\Table\CmsAuthorsCmsPagesTableTest" test case:
SQLSTATE[HY000]: General error: 1 near "CHECKSUM": syntax error in C:\xampp\htdocs\wa3\plugins\Psa\Cms\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php:337
```

## The solution

Check the used DB connection and
 * Throw an exception that fixturize can't work with an incompatible adaptor
 * Or fall back and don't use fixturize

```php
    protected function _hash(ConnectionInterface $db)
    {
        $driver = $db->getDriver();

        if (!$driver instanceof Mysql) {
            // Have no better idea right now to make it always regenerate the tables
            return microtime();
        }

        $sth = $db->execute("CHECKSUM TABLE " . $this->table . ';');
        $result = $sth->fetch('assoc');
        $checksum = $result['Checksum'];
        return $checksum;
    }
```

**Comment by jippi** [comment]
seems legit, PR welcome to check for compatible adapter(s)

**Comment by burzum** [comment]
@jippi do you know what other adaptors are compatible? I've checked PGSQL but it doesn't have a CHECKSUM method.

Implementing the hash for this would be a little more complicated http://stackoverflow.com/questions/4020033/how-can-i-get-a-hash-of-an-entire-table-in-postgresql

**Comment by jippi** [comment]
I've only ever used it against MySQL, i would be surprised if postgres don't have a round-about way to do it too :)

**Comment by burzum** [comment]
Well, check the SO question, I've spent a moment searching for a more easy and quick to implement way but haven't found one. I'm OK with MySQL only for now.

**Comment by ADmad** [comment]
Related PR has been merged.
