### ISSUE TITLE
About 2.0.0-beta version

### ISSUE THREAD

**Issue by T-Toshiya** [FriendsOfCake/fixturize#20]
I use CakePHP and friendsofcake/fixturize in my application.
Recently I'm planning to update CakePHP to 4.x but this plugin's 2.0.0 version is beta.
So do you have any plans to release 2.0.0 version in the near future?

**Comment by ravage84** [comment]
@ADmad could you please release a stable 2.0.0?

**Comment by ADmad** [comment]
Done
